/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 16 09:57:29 GMT 2021
 */

package com.org.apache.commons.collections.primitives;

import org.junit.Test;
import static org.junit.Assert.*;
import com.org.apache.commons.collections.primitives.ArrayIntList;
import com.org.apache.commons.collections.primitives.RandomAccessIntList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ArrayIntList_ES_preferences_Test extends ArrayIntList_ES_preferences_Test_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(0);
      arrayIntList0.add(0);
      ArrayIntList arrayIntList1 = new ArrayIntList(arrayIntList0);
      arrayIntList0.addAll(arrayIntList1);
      assertEquals(2, arrayIntList0.size());
      
      int int0 = arrayIntList0.removeElementAt(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(0);
      arrayIntList0.add(0, 0);
      int int0 = arrayIntList0.set(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(0);
      arrayIntList0.add(0);
      int[] intArray0 = arrayIntList0.toArray();
      assertArrayEquals(new int[] {0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(0);
      ArrayIntList arrayIntList1 = new ArrayIntList();
      RandomAccessIntList.RandomAccessIntSubList randomAccessIntList_RandomAccessIntSubList0 = new RandomAccessIntList.RandomAccessIntSubList(arrayIntList1, 0, 0);
      arrayIntList0.add(0);
      arrayIntList0.add((-1541));
      assertEquals(2, arrayIntList0.size());
      
      boolean boolean0 = arrayIntList0.retainAll(randomAccessIntList_RandomAccessIntSubList0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      arrayIntList0.add(0, 0);
      assertEquals(1, arrayIntList0.size());
      
      int int0 = arrayIntList0.set(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(0);
      boolean boolean0 = arrayIntList0.add(0);
      boolean boolean1 = arrayIntList0.add((-1));
      assertTrue(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(0);
      ArrayIntList arrayIntList1 = new ArrayIntList();
      RandomAccessIntList.RandomAccessIntSubList randomAccessIntList_RandomAccessIntSubList0 = new RandomAccessIntList.RandomAccessIntSubList(arrayIntList1, 0, 0);
      boolean boolean0 = arrayIntList0.add(0);
      arrayIntList0.add((-1));
      boolean boolean1 = arrayIntList0.retainAll(randomAccessIntList_RandomAccessIntSubList0);
      assertTrue(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(0);
      boolean boolean0 = arrayIntList0.add(0);
      boolean boolean1 = arrayIntList0.add(1796);
      assertTrue(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(0);
      ArrayIntList arrayIntList1 = new ArrayIntList();
      RandomAccessIntList.RandomAccessIntSubList randomAccessIntList_RandomAccessIntSubList0 = new RandomAccessIntList.RandomAccessIntSubList(arrayIntList1, 0, 0);
      arrayIntList0.add(0);
      boolean boolean0 = arrayIntList0.add(1815);
      boolean boolean1 = arrayIntList0.retainAll(randomAccessIntList_RandomAccessIntSubList0);
      assertTrue(boolean1 == boolean0);
  }
}
