/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 27 10:23:05 GMT 2022
 */

package com.org.apache.commons.collections.primitives;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.org.apache.commons.collections.primitives.ArrayIntList;
import com.org.apache.commons.collections.primitives.RandomAccessIntList;
import java.util.ConcurrentModificationException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ArrayIntList_ES_3_Test extends ArrayIntList_ES_3_Test_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList();
      RandomAccessIntList.RandomAccessIntSubList randomAccessIntList_RandomAccessIntSubList0 = new RandomAccessIntList.RandomAccessIntSubList(arrayIntList0, 0, 0);
      randomAccessIntList_RandomAccessIntSubList0.add((-4066));
      // Undeclared exception!
      try { 
        arrayIntList0.removeAll(randomAccessIntList_RandomAccessIntSubList0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.org.apache.commons.collections.primitives.RandomAccessIntList$ComodChecker", e);
      }
  }
}
