/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 16 09:35:35 GMT 2021
 */

package com.org.apache.commons.collections.primitives;

import org.junit.Test;
import static org.junit.Assert.*;
import com.org.apache.commons.collections.primitives.ArrayIntList;
import com.org.apache.commons.collections.primitives.RandomAccessIntList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ArrayIntList_ES_0_Test extends ArrayIntList_ES_0_Test_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArrayIntList arrayIntList0 = new ArrayIntList(0);
      ArrayIntList arrayIntList1 = new ArrayIntList();
      RandomAccessIntList.RandomAccessIntSubList randomAccessIntList_RandomAccessIntSubList0 = new RandomAccessIntList.RandomAccessIntSubList(arrayIntList1, 0, 0);
      arrayIntList0.add(0);
      arrayIntList0.add(1796);
      assertEquals(2, arrayIntList0.size());
      
      boolean boolean0 = arrayIntList0.retainAll(randomAccessIntList_RandomAccessIntSubList0);
      assertTrue(boolean0);
  }
}
